overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"
configuration:
  configuration: pyramid_excel.yaml
targets:
  - README.rst: custom_README.rst.jj2
  - setup.py: custom_setup.py.jj2
  - "docs/source/conf.py": "docs/source/conf.py"
  - .travis.yml: custom_travis.yml.jj2
  - MANIFEST.in: MANIFEST.in.jj2
  - "docs/source/index.rst": "docs/source/index.rst.jj2"
  - test.sh: test.script.jj2
  - test.bat: test.script.jj2
  - .gitignore: commons-gitignore.jj2