sudo: false
language: python
notifications:
  email: false
env:
  global:
python:
  - 2.7
  - 3.3
  - 3.4
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt --use-mirrors
script:
  make test
after_success:
  codecov
