sudo: false
language: python
notifications:
  email: false
env:
  - PYRAMID_VERSION=1.4.9
  - PYRAMID_VERSION=1.5.7
  - PYRAMID_VERSION=1.6.1
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
before_install:
  - pip install pyramid==$PYRAMID_VERSION
  - pip install -r tests/requirements.txt
script:
  make test
after_success:
  codecov