sudo: false
dist: xenial
language: python
notifications:
  email: false
env:
  - PYRAMID_VERSION=1.4.9
  - PYRAMID_VERSION=1.5.8
  - PYRAMID_VERSION=1.6.1
  - PYRAMID_VERSION=1.7.6
  - PYRAMID_VERSION=1.8.4
  - PYRAMID_VERSION=1.9
  - PYRAMID_VERSION=1.10.4
python:
  - 3.6
  - 3.7
  - 3.8

stages:
  - lint
  - moban
  - test


.lint: &lint
  git:
    submodules: false
  python: 3.6
  env:
    - MINREQ=0
  stage: lint
  script: make lint

.moban: &moban
  python: 3.6
  env:
    - MINREQ=0
  stage: moban
  install: pip install moban gitfs2 pypifs moban-jinja2-github moban-ansible
  script:
    - moban
    - git diff --exit-code

jobs:
  include:
    - *moban
    - *lint

stage: test

before_install:
  - if [ -n "$PYRAMID_VERSION" ]; then
      pip install pyramid==$PYRAMID_VERSION
    fi
  - if [[ -f min_requirements.txt && "$MINREQ" -eq 1 ]]; then
      mv min_requirements.txt requirements.txt ;
    fi
  - test ! -f rnd_requirements.txt ||
    pip install --no-deps -r rnd_requirements.txt
  - test ! -f rnd_requirements.txt || pip install -r rnd_requirements.txt ;
  - pip install -r tests/requirements.txt
script:
  - make test
after_success:
  codecov
