sudo: false
language: python
notifications:
  email: false
env:
  - PYRAMID_VERSION=1.4.9
  - PYRAMID_VERSION=1.5.8
  - PYRAMID_VERSION=1.6.1
  - PYRAMID_VERSION=1.7.6
  - PYRAMID_VERSION=1.8.4
  - PYRAMID_VERSION=1.9
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
before_install:
  - pip install pyramid==$PYRAMID_VERSION
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install flake8==2.6.2; fi
  - if [[ -f min_requirements.txt && "$MINREQ" -eq 1 ]]; then
      mv min_requirements.txt requirements.txt ;
    fi
  - pip install --upgrade setuptools "pip==7.1"
  - test ! -f rnd_requirements.txt || pip install --no-deps -r rnd_requirements.txt
  - test ! -f rnd_requirements.txt || pip install -r rnd_requirements.txt ;
  - pip install -r tests/requirements.txt
script:
  - make test
after_success:
  codecov
